//configs
export const HEARTBEAT_INTERVAL_MIN_VALUE = 120;
export const HEARTBEAT_INTERVAL_MAX_VALUE = 86400;
export const WEBSOCKET_PING_INTERVAL_MIN_VALUE = 20;
export const WEBSOCKET_PING_INTERVAL_MAX_VALUE = 86400;
export const GET_CONFIGURATION_MAX_KEYS_MIN_VALUE = 1;
export const GET_CONFIGURATION_MAX_KEYS_MAX_VALUE = 100;
export const METER_VALUE_SAMPLE_INTERVAL_MIN_VALUE = 10;
export const METER_VALUE_SAMPLE_INTERVAL_MAX_VALUE = 600;
export const CLOCK_ALIGNED_DATA_INTERVAL_MIN_VALUE = 0;
export const CLOCK_ALIGNED_DATA_INTERVAL_MAX_VALUE = 7200;

export const VOLTAGE = 230;
